

//SWIFT SKELETON CLASS: AccountDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

 class AccountDTO: Decodable, Mappable {

    // MARK: - Properties
	var accountID: Int?
	var accountNumber: String?
	var dateLastUpdated: Int32?
	var currentBalance: Double?
	var totalAccountAmount: Double?
	var cashAfterAccount: Double?
	var customerAccountName: String?
	var propertyAddress: String?
	var lastBillAmount: Double?
	var nextBillDate: Int32?
	var currentArrears: Double?
	var billDay: Int?
	var previousBillDate: Int32?
	var profileInfoID: Int?
    
    // MARK: - functions to conform to ObjectMapper protocol Mappable
     required init?(_ map: Map) {
    }
    
     func mapping(map: Map) {
        accountID <- map["accountID"]
        accountNumber <- map["accountNumber"]
        dateLastUpdated <- map["dateLastUpdated"]
        currentBalance <- map["currentBalance"]
        totalAccountAmount <- map["totalAccountAmount"]
        cashAfterAccount <- map["cashAfterAccount"]
        customerAccountName <- map["customerAccountName"]
        propertyAddress <- map["propertyAddress"]
        lastBillAmount <- map["lastBillAmount"]
        nextBillDate <- map["nextBillDate"]
        currentArrears <- map["currentArrears"]
        billDay <- map["billDay"]
        previousBillDate <- map["previousBillDate"]
        profileInfoID <- map["profileInfoID"]
    }
// MARK: - function to conform to Decodable

	 required init?(json: JSON) {
		self.accountID = "accountID" <~~ json
		self.accountNumber = "accountNumber" <~~ json
		self.dateLastUpdated = "dateLastUpdated" <~~ json
		self.currentBalance = "currentBalance" <~~ json
		self.totalAccountAmount = "totalAccountAmount" <~~ json
		self.cashAfterAccount = "cashAfterAccount" <~~ json
		self.customerAccountName = "customerAccountName" <~~ json
		self.propertyAddress = "propertyAddress" <~~ json
		self.lastBillAmount = "lastBillAmount" <~~ json
		self.nextBillDate = "nextBillDate" <~~ json
		self.currentArrears = "currentArrears" <~~ json
		self.billDay = "billDay" <~~ json
		self.previousBillDate = "previousBillDate" <~~ json
		self.profileInfoID = "profileInfoID" <~~ json
	}
    }
