

//SWIFT SKELETON CLASS: AlertDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class AlertDTO: Decodable, Mappable {

	// MARK: - Properties
	var alertID: Int?
	var municipalityID: Int?
	var municipalityStaffID: Int?
	var profileInfoID: Int?
	var updated: Int32?
	var stringDate: String?
	var id: Int?
	var description: String?
	var municipalityName: String?
	var profileName: String?
	var title: String?
	var alertData: String?
	var latitude: Double?
	var distance: Double?
	var longitude: Double?
	var thumbnailURL: String?
	var href: String?
	var activeFlag: Bool?
	var alertType: AlertDTO?
	var alertImageList: Array<AlertImageDTO>?

	// MARK: - functions to conform to ObjectMapper protocol Mappable
	required init?(_ map: Map) {
	}

	func mapping(map: Map) {
		alertID <- map["alertID"]
		municipalityID <- map["municipalityID"]
		municipalityStaffID <- map["municipalityStaffID"]
		profileInfoID <- map["profileInfoID"]
		updated <- map["updated"]
		id <- map["id"]
		description <- map["description"]
		municipalityName <- map["municipalityName"]
		profileName <- map["profileName"]
		title <- map["title"]
		stringDate <- map["stringDate"]
		alertData <- map["alertData"]
		latitude <- map["latitude"]
		distance <- map["distance"]
		longitude <- map["longitude"]
		thumbnailURL <- map["thumbnailURL"]
		href <- map["href"]
		activeFlag <- map["activeFlag"]
		alertType <- map["alertType"]
		alertImageList <- map["alertImageList"]
	}

	// MARK: - function to conform to Decodable
	required init?(json: JSON) {
		self.alertID = "alertID" <~~ json
		self.municipalityID = "municipalityID" <~~ json
		self.municipalityStaffID = "municipalityStaffID" <~~ json
		self.profileInfoID = "profileInfoID" <~~ json
		self.updated = "updated" <~~ json
		self.id = "id" <~~ json
		self.stringDate = "stringDate" <~~ json
		self.description = "description" <~~ json
		self.municipalityName = "municipalityName" <~~ json
		self.profileName = "profileName" <~~ json
		self.title = "title" <~~ json
		self.alertData = "alertData" <~~ json
		self.latitude = "latitude" <~~ json
		self.distance = "distance" <~~ json
		self.longitude = "longitude" <~~ json
		self.thumbnailURL = "thumbnailURL" <~~ json
		self.href = "href" <~~ json
		self.activeFlag = "activeFlag" <~~ json
		self.alertType = "alertType" <~~ json
		self.alertImageList = "alertImageList" <~~ json
	}
}
