

//SWIFT SKELETON CLASS: CityDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class CityDTO: Decodable,Mappable {

	var cityID: Int?
	var cityName: String?
	var latitude: Double?
	var longitude: Double?
	var provinceID: Int?
	var complaintList: Array<ComplaintDTO>?
    
     required init?(_ map: Map) {
    }
    
    func mapping(map: Map) {
        cityID <- map["cityID"]
        cityName <- map["cityName"]
        latitude <- map["latitude"]
        longitude <- map["longitude"]
        provinceID <- map["provinceID"]
        complaintList <- map["complaintList"]
    }

     required init?(json: JSON) {
		self.cityID = "cityID" <~~ json
		self.cityName = "cityName" <~~ json
		self.latitude = "latitude" <~~ json
		self.longitude = "longitude" <~~ json
		self.provinceID = "provinceID" <~~ json
		self.complaintList = "complaintList" <~~ json
	}
}
