

//SWIFT SKELETON CLASS: ContactDepartmentDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class ContactDepartmentDTO: Decodable,Mappable {

	var contactDepartmentID: Int?
	var contactDepartmentName: String?
	var contactList: Array<ContactDTO>?

     required init?(_ map: Map) {
    }
    
    func mapping(map: Map) {
        contactDepartmentID <- map["contactDepartmentID"]
        contactDepartmentName <- map["contactDepartmentName"]
        contactList <- map["contactList"]
    }

	 required init?(json: JSON) {
		self.contactDepartmentID = "contactDepartmentID" <~~ json
		self.contactDepartmentName = "contactDepartmentName" <~~ json
		self.contactList = "contactList" <~~ json
	}
}
