

//SWIFT SKELETON CLASS: CountryDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class CountryDTO: Decodable, Mappable {

	var countryID: Int?
	var countryName: String?

	required init?(json: JSON) {
		self.countryID = "countryID" <~~ json
		self.countryName = "countryName" <~~ json
	}
	required init?(_ map: Map) {
	}

	func mapping(map: Map) {
		countryID <- map["countryID"]
		countryName <- map["countryName"]
	}
}
