

//SWIFT SKELETON CLASS: CustomerStatusDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class CustomerStatusDTO: Decodable,Mappable {

	var customerStatusID: Int?
	var customerStatusName: String?
	var profileInfoList: Array<ProfileInfoDTO>?

	 required init?(json: JSON) {
		self.customerStatusID = "customerStatusID" <~~ json
		self.customerStatusName = "customerStatusName" <~~ json
		self.profileInfoList = "profileInfoList" <~~ json
	}
     required init?(_ map: Map) {
    }
    
    func mapping(map: Map) {
        customerStatusID <- map["customerStatusID"]
        customerStatusName <- map["customerStatusName"]
        profileInfoList <- map["profileInfoList"]
    }
}
