

//SWIFT SKELETON CLASS: CustomerTypeDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class CustomerTypeDTO: Decodable,Mappable {

	var customerTypeID: Int?
	var customerTypeName: String?
	var profileInfoList: Array<ProfileInfoDTO>?

	 required init?(json: JSON) {
		self.customerTypeID = "customerTypeID" <~~ json
		self.customerTypeName = "customerTypeName" <~~ json
		self.profileInfoList = "profileInfoList" <~~ json
	}
    
     required init?(_ map: Map) {
    }
    
    func mapping(map: Map) {
        customerTypeID <- map["customerTypeID"]
        customerTypeName <- map["customerTypeName"]
        profileInfoList <- map["profileInfoList"]
    }
}
