

//SWIFT SKELETON CLASS: FaqDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class FaqDTO: Decodable,Mappable {

    // MARK: - Properties
	var faqID: Int?
	var question: String?
	var answer: String?
	var dateUpdated: Int32?
	var activeFlag: Bool?
	var sequenceNumber: Int?
	var municipalityID: Int?
    var faqType: FreqQuestionTypeDTO?
    
    // MARK: - functions to conform to Decodable
	 required init?(json: JSON) {
		self.faqID = "faqID" <~~ json
		self.question = "question" <~~ json
		self.answer = "answer" <~~ json
		self.dateUpdated = "dateUpdated" <~~ json
		self.activeFlag = "activeFlag" <~~ json
		self.sequenceNumber = "sequenceNumber" <~~ json
		self.municipalityID = "municipalityID" <~~ json
		
	}
    // MARK: - functions to conform to ObjectMapper protocol Mappable
     required init?(_ map: Map) {
    }
    
    func mapping(map: Map) {
        faqID <- map["faqID"]
        question <- map["question"]
        answer <- map["answer"]
        dateUpdated <- map["dateUpdated"]
        activeFlag <- map["activeFlag"]
        sequenceNumber <- map["sequenceNumber"]
        municipalityID <- map["municipalityID"]
        faqType <- map["faqType"]
    }
    

}
