

//SWIFT SKELETON CLASS: GISAddressDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class GISAddressDTO: Decodable,Mappable {

    // MARK: - Properties
	var street: String?
	var suburb: String?
	var city: String?
    
     required init() {
        
    }
    // MARK: - functions to conform to Decodable
	 required init?(json: JSON) {
		self.street = "street" <~~ json
		self.suburb = "suburb" <~~ json
		self.city = "city" <~~ json
	}
    
    // MARK: - functions to conform to ObjectMapper protocol Mappable
    
    required init?(_ map: Map) {
    }
    
    func mapping(map: Map) {
        street <- map["street"]
        suburb <- map["suburb"]
        city <- map["city"]
    }
}
