

//SWIFT SKELETON CLASS: MunicipalityDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class MunicipalityDTO: Decodable, Mappable {

	// MARK: -  Properties
	var serviceURI: String?
	var municipalityID: Int?
	var countryID: Int?
	var municipalityName: String?
	var countryName: String?
	var email: String?
	var cellphone: String?
	var latitude: Double?
	var longitude: Double?
	var dateRegistered: Int32?
	var activeFlag: Bool?
	var municipalityCityList: Array<MunicipalityCityDTO>?
	var alertTypeList: Array<AlertTypeDTO>?
	var profileInfoList: Array<ProfileInfoDTO>?
	var alertList: Array<AlertDTO>?
	var complaintList: Array<ComplaintDTO>?
	var complaintTypeList: Array<ComplaintTypeDTO>?
	var faqList: Array<FaqDTO>?
	var userList: Array<UserDTO>?

	required init() { }

	// MARK: - functions to conform to ObjectMapper protocol Mappable
	required init?(_ map: Map) {
	}

	func mapping(map: Map) {
		serviceURI <- map["serviceURI"]
		municipalityID <- map["municipalityID"]
		countryID <- map["countryID"]
		municipalityName <- map["municipalityName"]
		countryName <- map["countryName"]
		email <- map["email"]
		cellphone <- map["cellphone"]
		latitude <- map["latitude"]
		longitude <- map["longitude"]
		dateRegistered <- map["dateRegistered"]
		activeFlag <- map["activeFlag"]
		municipalityCityList <- map["municipalityCityList"]
		alertTypeList <- map["alertTypeList"]
		profileInfoList <- map["profileInfoList"]
		alertList <- map["alertList"]
		complaintList <- map["complaintList"]
		complaintTypeList <- map["complaintTypeList"]
		faqList <- map["faqList"]
		userList <- map["userList"]
	}

	// MARK: - functions to conform to Decodable

	required init?(json: JSON) {
		self.serviceURI = "serviceURI" <~~ json
		self.municipalityID = "municipalityID" <~~ json
		self.countryID = "countryID" <~~ json
		self.municipalityName = "municipalityName" <~~ json
		self.countryName = "countryName" <~~ json
		self.email = "email" <~~ json
		self.cellphone = "cellphone" <~~ json
		self.latitude = "latitude" <~~ json
		self.longitude = "longitude" <~~ json
		self.dateRegistered = "dateRegistered" <~~ json
		self.activeFlag = "activeFlag" <~~ json
		self.municipalityCityList = "municipalityCityList" <~~ json
		self.alertTypeList = "alertTypeList" <~~ json
		self.profileInfoList = "profileInfoList" <~~ json
		self.alertList = "alertList" <~~ json
		self.complaintList = "complaintList" <~~ json
		self.complaintTypeList = "complaintTypeList" <~~ json
		self.faqList = "faqList" <~~ json
		self.userList = "userList" <~~ json
	}
}
