

//SWIFT SKELETON CLASS: MunicipalityCityDTO
//Generated by Java2Swift on Sat Apr 23 10:25:46 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class MunicipalityCityDTO: Decodable,Mappable {

    // MARK: - Properties
	var municipalityCityID: Int?
	var municipalityID: Int?
    var city: CityDTO?

    // MARK: - functions to conform to Decodable
	 required init?(json: JSON) {
		self.municipalityCityID = "municipalityCityID" <~~ json
		self.city = "city" <~~ json
		self.municipalityID = "municipalityID" <~~ json
	}
    
    // MARK: - functions to conform to ObjectMapper protocol Mappable
     required init?(_ map: Map) {
    }
    
    func mapping(map: Map) {
        municipalityCityID <- map["municipalityCityID"]
        city <- map["city"]
        municipalityID <- map["municipalityID"]
    }
   
}
