

//SWIFT SKELETON CLASS: PhotoUploadDTO
//Generated by Java2Swift on Sat Apr 23 10:22:54 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class PhotoUploadDTO: Decodable, Mappable {

	// MARK: - Properties
	var complaintImage: ComplaintImageDTO?
	var municipalityID: Int?

	init() {

	}
    // MARK: - functions to conform to ObjectMapper protocol Mappable
     required init?(_ map: Map) {
        
    }
	// MARK: - function to conform to Decodable
	 required init?(json: JSON) {
		self.municipalityID = "municipalityID" <~~ json
		self.complaintImage = "complaintImage" <~~ json
	}
	
	 func mapping(map: Map) {
		complaintImage <- map["complaintImage"]
		municipalityID <- map["municipalityID"]
	}
}
