

//SWIFT SKELETON CLASS: RequestList
//Generated by Java2Swift on Sat Apr 23 10:22:54 SAST 2016

import Foundation
import Gloss

class RequestList: Decodable, Glossy {

	var requestList: Array<RequestDTO>?

	internal required init?(json: JSON) {
		self.requestList = "requestList" <~~ json
	}
	func toJSON() -> JSON? {
		let jx = jsonify([
			"requestList" ~~> self.requestList,
		])
		return jx!
	}

}
