

//SWIFT SKELETON CLASS: Notifier
//Generated by Java2Swift on Sat Apr 23 10:22:54 SAST 2016

import Foundation
import Gloss
import ObjectMapper

class Notifier: Decodable {

	// MARK: - Properties
	var color: Int?
	var message: String?
	var alert: AlertDTO?

	// MARK: - functions to conform to Decodable
	required init?(json: JSON) {
		self.color = "color" <~~ json
		self.message = "message" <~~ json
		self.alert = "alert" <~~ json
	}

	// MARK: - functions to conform to ObjectMapper protocol Mappable
	required init?(_ map: Map) {
	}

	func mapping(map: Map) {
		message <- map["message"]
		alert <- map["alert"]
		color <- map["color"]
	}
}
