fastlane_version "1.110.0"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'SmartCity-iOS-App', export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['nkululeko@avsoft.co.za', 'aubreym@oneconnectgroup.com', 'rogers@oneconnect.co.za', 'andre@oneconnectgroup.com', 'suvashen@oneconnectgroup.com', 'clive@oneconnect.co.za'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '8419153fba562e57532d0502ff0e71266daa9d2b',
             build_secret: '893db73d5b10829cf8bc486462762d54ad7a570dda80a3ea593d55effd94647a',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end
